### PR TITLE
chore(i18n): add more languages

### PR DESCRIPTION
**Pull request by Yoiber071**
Add Transifex Working Group languages.

New language codes: fr_CA,it_IT,pt_PT,de_DE,uk,ru,hi

@feanil 
@natabene 

When executing the **make pull_translations** command, some files are automatically modified.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Yoiber071!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@mphilbrick211 tests run.

**Comment by natabene** [comment]
I am curious, why am I being tagged?

**Comment by e0d** [comment]
@Yoiber071 looks like there are test failures.

**Comment by Yoiber071** [comment]
> I am curious, why am I being tagged?

My apologies @natabene, I had only been following this previous PR https://github.com/openedx/frontend-app-authn/pull/463 😄

**Comment by Yoiber071** [comment]
Hi @e0d , Sorry for the late response, I've fixed the lint failures and is ready to be tested again.

**Comment by e0d** [comment]
I've run the tests.  General question for @brian-smith-tcril and @Yoiber071 I notice that in this PR many of the language specific strings are using the English original.  I suppose this is because we don't have translations yet.  I wanted to make sure that:
-  we have a way of flagging that to the translators and 
- that this is the best option that we currently have

**Comment by mphilbrick211** [comment]
> I've run the tests. General question for @brian-smith-tcril and @Yoiber071 I notice that in this PR many of the language specific strings are using the English original. I suppose this is because we don't have translations yet. I wanted to make sure that:
> 
> * we have a way of flagging that to the translators and
> * that this is the best option that we currently have

Hi @brian-smith-tcril and @Yoiber071! Friendly ping on Ed's question above.

**Comment by mphilbrick211** [comment]
> > I've run the tests. General question for @brian-smith-tcril and @Yoiber071 I notice that in this PR many of the language specific strings are using the English original. I suppose this is because we don't have translations yet. I wanted to make sure that:
> > 
> > * we have a way of flagging that to the translators and
> > * that this is the best option that we currently have
> 
> Hi @brian-smith-tcril and @Yoiber071! Friendly ping on Ed's question above.

@brian-smith-tcril @Yoiber071 - just checking in on this!

**Comment by brian-smith-tcril** [comment]
I'm pretty sure the pattern of "make a new json file that just has `{}` in it" is what we're supposed to follow for transifex. I don't think manually adding translations via PR is a pattern we're using.

**Comment by mphilbrick211** [comment]
Hi @e0d @brian-smith-tcril @Yoiber071 - just checking in to see if there are any next steps here?

**Comment by brian-smith-tcril** [comment]
I'd like to confirm that I understand how this PR got into this state. It seems `make pull_translations` was run manually and then those changes were committed.

I don't think that's a pattern we should be following.

However, when looking through the history of https://github.com/openedx/frontend-app-support-tools/tree/master/src/i18n, it seems translations have never been updated. I'm assuming that means automated pulls from transifex were never set up for this repo.

I see a couple options for paths forward:
#### A: Set up the automated translations pulling using the old method
* This seems less than ideal to me, since the work for [OEP-58](https://docs.openedx.org/projects/openedx-proposals/en/latest/architectural-decisions/oep-0058-arch-translations-management.html) should replace the need for that shortly.
#### B: Manually run `make pull_translations` and make PRs with updates when strings are updated in transifex
* The "manual" aspect of this doesn't feel great, but it does seem like a quite simple short term solution

If people are OK with moving forward with the manual plan **B**, then one more manual run of `make pull_translations` on this PR should make it good to go.

If we instead go with plan **A**, all of the changes *modifying* `.json` files in `/src/i18n/messages` will need to be reverted, and the new `.json` files should be added containing `{}` instead of any strings. Then, once the automation kicks off, the json files in there would automatically be updated to contain the up to date translations from transifex.

**Comment by Yoiber071** [comment]
Hello, yes it's correct I have run `make pull_translations` manually and JSON `{}` was added automatically, so @mphilbrick211 I look forward to hearing from you to find out how you want to continue regarding the @brian-smith-tcril response.

**Comment by mphilbrick211** [comment]
> Hello, yes it's correct I have run `make pull_translations` manually and JSON `{}` was added automatically, so @mphilbrick211 I look forward to hearing from you to find out how you want to continue regarding the @brian-smith-tcril response.

Thanks, @Yoiber071 - this is not my area of expertise, so I will leave it to @brian-smith-tcril to advise on next steps. @brian-smith-tcril - is there someone else you'd like to have weigh in on this?

**Comment by brian-smith-tcril** [comment]
> is there someone else you'd like to have weigh in on this?

Nobody specific comes to mind immediately, I'll bring it up at standup tomorrow and have either a decision or person to ask after.

**Comment by brian-smith-tcril** [comment]
Sounds like everyone is happy with plan B! That means one more manual run of `make pull_translations` and this PR should be good to go!

**Comment by mphilbrick211** [comment]
Hi all, just following up on this.

@Yoiber071 - looks like some branch conflicts need to be resolved. Thanks!

**Comment by mphilbrick211** [comment]
> Hi all, just following up on this.
> 
> @Yoiber071 - looks like some branch conflicts need to be resolved. Thanks!

Hi @Yoiber071! Friendly ping on this.

**Comment by mphilbrick211** [comment]
Hi @Yoiber071! Just following up on the branch conflicts. Please let us know if you still plan to pursue this PR. Thanks!

**Comment by Yoiber071** [comment]
> Hi @mphilbrick211 
The conflicts have been resolved on the branch.

**Comment by mphilbrick211** [comment]
Hi @brian-smith-tcril! Branch conflicts were just resolved on this, would you mind enabling tests again if possible, and reviewing?

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by mphilbrick211** [comment]
hi @AliAdnanSohail! Is this something you, or a member of your team could please review and merge for us? Thank you!

**Comment by mphilbrick211** [comment]
> hi @AliAdnanSohail! Is this something you, or a member of your team could please review and merge for us? Thank you!

Hi @AliAdnanSohail - just checking in on this.

**Review by Ali-D-Akbar — APPROVED** [review]

**Review by AliAdnanSohail — APPROVED** [review]

**Pull request merged**
